# Setup
title:               Dougie's Diary
tagline:             'How I see'
description:         'Everything I know'
url:                 https://delphinh.github.io/
baseurl:             'https://delphinh.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dougie Hwang
  url:               https://twitter.com/sleep_redfox
  email:             duckling4579@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
